### ISSUE TITLE
Variable substitution: should be an empty string when variable not found

### ISSUE THREAD

**Issue by DominicWatson** [pixl8/cfflow#3]
e.g.

```yaml
condition:
  ref: string.IsEmpty
  args:
     value: $variableInState
```

When `variableInState` does not exist in the state, the condition above should be true. Currently, the `value` string is passed as `$variableInState`.
